image: maven:3.6-jdk-11-slim

variables:
  # MYSQL
  MYSQL_USER: "albumstore"
  MYSQL_PASSWORD: "albumstore"
  MYSQL_DATABASE: "albumstore"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  # RAVEN
  MYSQL_PORT: "3306"
  MYSQL_HOST: "localhost"
  # MAVEN
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

services:
- mysql:5.7

stages:
- build

build:
  stage: build
  script:
  - mvn dependency:go-offline -q -s settings.xml
  - mvn test verify jacoco:report -s settings.xml
  - cat target/site/jacoco/index.html
  artifacts:
    paths:
    - target/surefire-reports
    expire_in: 30 days

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .m2/repository
