app:
  env: ${ALBUMSTORE_ENV:development}
  name: albumstore
  description: Albumstore is an API to manager Discs and Sales
  version: 0.0.1
  contact: Ramon Pereira
  url: https://www.linkedin.com/in/ramon-pereira-94a04b107/
  email: ramon.alves@live.com
spotify:
  clientId: ${ALBUMSTORE_SPOTIFY_CLIENT_ID:default}
  clientSecret: ${ALBUMSTORE_SPOTIFY_CLIENT_SECRET:default}
spring:
  datasource:
    url: ${ALBUMSTORE_DATASOURCE_URL}
    username: ${ALBUMSTORE_DATASOURCE_USERNAME}
    password: ${ALBUMSTORE_DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect