---
version: 2
jobs:
  build:
    working_directory: /java/src/github.com/r4monrp/albumstore
    docker:
    - image: maven:3.6-jdk-11-slim
      environment:
        #### MYSQL ####
        MYSQL_USER: albumstore
        MYSQL_PASSWORD: albumstore
        MYSQL_DATABASE: albumstore
        MYSQL_PORT: 3306
        MYSQL_HOST: localhost
    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: albumstore
        MYSQL_DATABASE: albumstore
        MYSQL_USER: albumstore
        MYSQL_PASSWORD: albumstore
    steps: # a collection of executable commands
    - checkout # check out source code to working directory

    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        key: albumstore-{{ checksum "pom.xml" }}

    - run: mvn -s settings.xml dependency:go-offline # gets the project dependencies

    - save_cache: # saves the project dependencies
        paths:
        - ~/.m2
        key: albumstore-{{ checksum "pom.xml" }}

    #- run: mvn -s settings.xml -q test verify coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN package # run the actual tests
    - run: mvn -s settings.xml -q test verify package

    - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
        path: target/surefire-reports

    - store_artifacts: # store the uberjar as an artifact
        path: target/albumstore*.jar
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
