version: 2
jobs:
  build:
    working_directory: /java/src/github.com/r4monrp/albumstore
    docker:
      - image: maven:3.6-jdk-11-slim
        environment:
          #### MYSQL ####
          MYSQL_USER: albumstore
          MYSQL_PASSWORD: '!@12QWqw'
          MYSQL_DATABASE: albumstore
          MYSQL_PORT: 3306
          MYSQL_HOST: localhost
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: albumstore
          MYSQL_DATABASE: albumstore
          MYSQL_USER: albumstore
          MYSQL_PASSWORD: '!@12QWqw'
    steps:
      - run:
          command: mvn clean install

      - store_artifacts: # store the uberjar as an artifact
          path: target/albumstore*.jar
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples